### ISSUE TITLE
shift + left arrow doesn't decrement FRQ

### ISSUE THREAD

**Issue by hoops-doggit** [hundredrabbits/Marabu#12]
It works using [ and ] but not shift + left arrow.

I'm using it on windows. could just be a platform issue?

**Comment by neauoire** [comment]
It might be, let me have a look :)

**Comment by isackender** [comment]
Yeah, shift+LeftArrow doesn't work in:
FRQ (LFO)
DIS (Shapers)

**Comment by neauoire** [comment]
Fixed 👍
