### ISSUE TITLE
Chord with more than two notes?

### ISSUE THREAD

**Issue by dcposch** [hundredrabbits/Marabu#13]
how do you add multiple notes? shift+(note) only lets me add two as far as i can tell

how do you even add notes to anything past the first column? alt+(left right) just takes me to a completely new screen for instrument 2...

**Comment by neauoire** [comment]
arrow down?
Press tab otherwise, to have the horizontal view.
Or better, press `ctrl+k 4` and then `asdfg`.

**Comment by neauoire** [comment]
Oh sorry I misread. You cannot make chords with more than 2 notes at the moment. Marabu has only 32 voices in total.
