### ISSUE TITLE
Bug: Decrement/increment note value doesn't wrap; overflows MIDI standard

### ISSUE THREAD

**Issue by composition4** [hundredrabbits/Marabu#6]
Use of `increment note` and `decrement note` (even on blank fields) can create a note outside of MIDI standard -- e.g.: `C-2`, `C-10`.

[Possible feature, not bug]

**Comment by neauoire** [comment]
Clamped between octave 3-8
https://github.com/hundredrabbits/Marabu/commit/0262e870fbc87574a2465a296643b353186fd8d0
